### ISSUE TITLE
Telecon agenda for June 19, 2020

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1507]
# Documentation:
- [x] #1529: [Discussion] Switch examples back to RST files?  
- [ ] #1513: [Discussion] How to best ensure the examples are numerous, helpful and high quality?  

# Features: 
- [x] #1308: [Enhancement] Update conduit models to return element values as well as overall conduit value
- [ ] #1505: [Discussion] Use pore-scale models for health/consistency checks (also #1469)
- [x] #1428: [Enhancement] Adding a Continuum class to the ``geometry`` module
- [ ] #1504: [Enhancement] Add conns and coords at network attributes

# Package Maintenance
- [x] #1521: [Discussion] Remove dev and use master as the development branch
- [ ] #1405: [Discussion] Parameters in pore-scale model (@ma-sadeghi)
- [ ] #1363: [Discussion] Pore-scale model factory for users to make models more easily (@ma-sadeghi)

# Implementation
- [ ] #1506: [Discussion] Late pore filling as an 'iterative prop'
- [ ] #1455: [Discussion] Depth of dependency graph
- [x] #1354: [Discussion] Non-invasively update physics/phase inside algorithms

# Bugs
- [x] Fix up the plotting functions in ``topotools`` (#1470, #1475) 
- [ ] #1481: [Bug] NP accept with multiple physics (@magnaou)
- [ ] #1512: [Possible Bug]: NP algorithms don't have `results` method implemented (@magnao)
