### ISSUE TITLE
Telecon Agenda for June 26, 2020

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1541]
# Documentation:
- [ ] [Discussion] Progress on Notebook examples

# Development
- [ ] #1521: Remove dev branch, remain master to main (or other options?)
- [ ] #1354: [Discussion] Non-invasively update physics/phase inside algorithms.  Related: #1405, #1325, 

# Bugs
- [ ] #1481: [Bug] NP accept with multiple physics
- [ ] #1512: [Possible Bug]: NP algorithms don't have `results` or `rate` method implemented
- [ ] Multiphase and partitioning bugs
