### ISSUE TITLE
Telecon Agenda - July 17, 2020

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1586]
- [x] Status of examples_galore
- [x] Update on conductance models #1421, #1570 @Ni2M 
- [x] DNS or Continuum Geometry class #1428 @mkaguer 
- [x] Throat volume in transient sims #1459 @magnaou 
- [x] Multiple physics in PNP #1481
- [x] Overview of high priority bugs: #1526, #1501,
